### PR TITLE
fix iterator invalidation issue by storing indices not iterators

### LINKED ISSUE #50: `slice_of` internal iterators get invalidated on move
Even a simple case like `buffers::slice_of<buffers::const_buffer_pair>` breaks on move, so we can't keep it as a member variable inside composed operations.
https://github.com/cppalliance/buffers/blob/908fc2e6839667007b8ec379d2ad68cfdb9fb3fc/include/boost/buffers/slice.hpp#L67-L73

### PR DESCRIPTION
**Pull request by MungoG**

### CODE REVIEW

**Comment by ashtum** [comment]
Does this buffer type has proper test cases for move and copy operations? It's odd that it has been passing the tests before this change.

File: test/unit/test_buffers.hpp [hunk 1]
```diff
@@ -265,13 +265,37 @@ grind_front(
             remove_prefix(bs, n);
             check_eq(bs, pat);
             check_iterators(bs, pat);
+
+            if(n == pat0.size() / 2 && pat != pat0)
```
Comment (ashtum) [inline test/unit/test_buffers.hpp]: Is `n == pat0.size() / 2` for performance reasons? How lengthy are these patterns, couldn't it just run on each iteration?

Comment (MungoG) [reply test/unit/test_buffers.hpp]: Yes. Reducing the test string length also made it quick enough to complete (after a few minutes).

Comment (ashtum) [reply test/unit/test_buffers.hpp]: Isn't it because of recursion? Since it calls `grind_front` again, the `n == pat0.size() / 2` condition somehow prevents exponential iterations. And because the pattern length is so limited, we don't get a stack overflow.

Comment (MungoG) [reply test/unit/test_buffers.hpp]: The version that does everything ends up with an o(n^n) complexity. To make it clearer that this is for performance reasons, I've changed the recursion to a single level (which successfully demonstrates a core dump on the original version with stored iterators).

File: test/unit/CMakeLists.txt [hunk 2]
```diff
@@ -7,24 +7,29 @@
 # Official repository: https://github.com/cppalliance/buffers
 #
 
-add_subdirectory(../../../url/extra/test_suite test_suite)
+set(EXTRAFILES
+    ../../../url/extra/test_suite/test_main.cpp
+    ../../../url/extra/test_suite/test_suite.cpp
+    ../../../url/extra/test_suite/test_suite.hpp
+    )
```
Comment (ashtum) [inline test/unit/CMakeLists.txt]: Please use the following workaround instead:
```Cmake
if (NOT TARGET boost_url_test_suite)
    add_subdirectory(../../../url/extra/test_suite test_suite)
endif ()
```
This reduces the maintenance burden until we find a proper solution.

File: test/unit/test_buffers.hpp [hunk 3]
```diff
@@ -307,8 +358,12 @@ check_slice(
...
     core::string_view pat)
 {
-    grind_front(bs, pat);
-    grind_back(bs, pat);
+    {
+        grind_front(bs, pat, 1);
+    }
+    {
+        grind_back(bs, pat, 1);
+    }
```
Comment (ashtum) [inline test/unit/test_buffers.hpp]: What are these scopes for? Are they for consistency?

Comment (MungoG) [reply test/unit/test_buffers.hpp]: Removed

File: test/unit/CMakeLists.txt (hunk 2 above)
Comment (MungoG) [reply test/unit/CMakeLists.txt]: Done
